name: 'aqi_crops_pipeline'
version: '1.0.0'
config-version: 2

# This must match your dbt Cloud profile name
profile: 'default'

# Paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  aqi_crops_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table
